# Generated by Django 5.0.2 on 2024-03-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
